import { useCallback, useEffect, useState } from 'react'
import { createDashboardMatch, createDashboardTeam, createDashboardTournament, deleteDashboardMatch, deleteDashboardTeam, deleteDashboardTournament, fetchDashboardMatches, fetchDashboardTeams, fetchDashboardTournaments, getApiErrorMessage } from '../services/api'

const inputClass = 'w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300'

function Notice({ error }) { return error ? <div role="alert" className="mb-5 rounded-lg border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</div> : null }
function Field({ label, children }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-[0.12em] text-slate-400">{label}</span>{children}</label> }

export default function AdminTools({ activeTab }) {
  if (activeTab === 'tournaments') return <TournamentTools />
  if (activeTab === 'teams') return <TeamTools />
  return <MatchTools />
}

function TournamentTools() {
  const [items, setItems] = useState([]); const [error, setError] = useState(''); const [form, setForm] = useState({ name: 'MLBB Campus Clash', description: '', prize_pool: '3500', start_date: '', end_date: '', registration_deadline: '', game_mode: '5v5 Draft Pick', max_teams: '32' })
  const load = useCallback(async () => { try { setItems(await fetchDashboardTournaments()) } catch (e) { setError(getApiErrorMessage(e, 'Unable to load tournaments.')) } }, [])
  useEffect(() => { load() }, [load])
  async function submit(event) { event.preventDefault(); try { await createDashboardTournament({ ...form, max_teams: Number(form.max_teams), prize_pool: Number(form.prize_pool) }); setForm({ ...form, name: '', description: '' }); await load() } catch (e) { setError(getApiErrorMessage(e, 'Unable to create tournament.')) } }
  return <ToolPanel eyebrow="Tournament setup" title="Manage tournaments"><Notice error={error} /><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Field label="Name"><input required className={inputClass} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Game mode"><input required className={inputClass} value={form.game_mode} onChange={(e) => setForm({ ...form, game_mode: e.target.value })} /></Field><Field label="Prize pool"><input required type="number" min="0" className={inputClass} value={form.prize_pool} onChange={(e) => setForm({ ...form, prize_pool: e.target.value })} /></Field><Field label="Maximum teams"><input required type="number" min="2" className={inputClass} value={form.max_teams} onChange={(e) => setForm({ ...form, max_teams: e.target.value })} /></Field><Field label="Start date"><input required type="date" className={inputClass} value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })} /></Field><Field label="End date"><input required type="date" className={inputClass} value={form.end_date} onChange={(e) => setForm({ ...form, end_date: e.target.value })} /></Field><Field label="Registration deadline"><input required type="datetime-local" className={inputClass} value={form.registration_deadline} onChange={(e) => setForm({ ...form, registration_deadline: e.target.value })} /></Field><Field label="Description"><input className={inputClass} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><button className="rounded-lg bg-cyan-400 px-4 py-3 text-sm font-black uppercase tracking-[0.12em] text-slate-950 md:col-span-2">Create tournament</button></form><ItemList items={items} empty="No tournaments yet." onDelete={async (id) => { await deleteDashboardTournament(id); await load() }} render={(item) => <><strong>{item.name}</strong><span>{item.team_count} / {item.max_teams} teams · {item.game_mode}</span></>} /></ToolPanel>
}

function TeamTools() {
  const [items, setItems] = useState([]); const [tournaments, setTournaments] = useState([]); const [error, setError] = useState(''); const [form, setForm] = useState({ tournament: '', name: '', captain_name: '', email: '', phone_number: '' })
  const load = useCallback(async () => { try { const [teams, events] = await Promise.all([fetchDashboardTeams(), fetchDashboardTournaments()]); setItems(teams); setTournaments(events); if (!form.tournament && events[0]) setForm((current) => ({ ...current, tournament: events[0].id })) } catch (e) { setError(getApiErrorMessage(e, 'Unable to load teams.')) } }, [form.tournament])
  useEffect(() => { load() }, [load])
  async function submit(event) { event.preventDefault(); try { await createDashboardTeam({ ...form, tournament: Number(form.tournament) }); setForm({ ...form, name: '', captain_name: '', email: '', phone_number: '' }); await load() } catch (e) { setError(getApiErrorMessage(e, 'Unable to create team.')) } }
  return <ToolPanel eyebrow="Roster management" title="Registered teams"><Notice error={error} /><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Field label="Tournament"><select required className={inputClass} value={form.tournament} onChange={(e) => setForm({ ...form, tournament: e.target.value })}><option value="">Select tournament</option>{tournaments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Team name"><input required className={inputClass} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Captain name"><input required className={inputClass} value={form.captain_name} onChange={(e) => setForm({ ...form, captain_name: e.target.value })} /></Field><Field label="Email"><input required type="email" className={inputClass} value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="Phone"><input required className={inputClass} value={form.phone_number} onChange={(e) => setForm({ ...form, phone_number: e.target.value })} /></Field><button className="rounded-lg bg-cyan-400 px-4 py-3 text-sm font-black uppercase tracking-[0.12em] text-slate-950 md:col-span-2">Add team</button></form><ItemList items={items} empty="No registered teams yet." onDelete={async (id) => { await deleteDashboardTeam(id); await load() }} render={(item) => <><strong>{item.name}</strong><span>{item.captain_name} · {item.players?.length || 0} players · {item.email}</span></>} /></ToolPanel>
}

function MatchTools() {
  const [items, setItems] = useState([]); const [teams, setTeams] = useState([]); const [tournaments, setTournaments] = useState([]); const [error, setError] = useState(''); const [form, setForm] = useState({ tournament: '', stage: 'Quarter Final', team_one: '', team_two: '', scheduled_at: '', best_of: '3' })
  const load = useCallback(async () => { try { const [matches, teamItems, eventItems] = await Promise.all([fetchDashboardMatches(), fetchDashboardTeams(), fetchDashboardTournaments()]); setItems(matches); setTeams(teamItems); setTournaments(eventItems) } catch (e) { setError(getApiErrorMessage(e, 'Unable to load matches.')) } }, [])
  useEffect(() => { load() }, [load])
  async function submit(event) { event.preventDefault(); try { await createDashboardMatch({ ...form, tournament: Number(form.tournament), team_one: form.team_one ? Number(form.team_one) : null, team_two: form.team_two ? Number(form.team_two) : null, best_of: Number(form.best_of) }); setForm({ ...form, stage: 'Quarter Final', team_one: '', team_two: '', scheduled_at: '' }); await load() } catch (e) { setError(getApiErrorMessage(e, 'Unable to create match.')) } }
  return <ToolPanel eyebrow="Fixture management" title="Schedule matches"><Notice error={error} /><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Field label="Tournament"><select required className={inputClass} value={form.tournament} onChange={(e) => setForm({ ...form, tournament: e.target.value })}><option value="">Select tournament</option>{tournaments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Stage"><input required className={inputClass} value={form.stage} onChange={(e) => setForm({ ...form, stage: e.target.value })} /></Field><Field label="Team one"><select className={inputClass} value={form.team_one} onChange={(e) => setForm({ ...form, team_one: e.target.value })}><option value="">TBD</option>{teams.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Team two"><select className={inputClass} value={form.team_two} onChange={(e) => setForm({ ...form, team_two: e.target.value })}><option value="">TBD</option>{teams.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Scheduled time"><input required type="datetime-local" className={inputClass} value={form.scheduled_at} onChange={(e) => setForm({ ...form, scheduled_at: e.target.value })} /></Field><Field label="Best of"><select className={inputClass} value={form.best_of} onChange={(e) => setForm({ ...form, best_of: e.target.value })}><option value="1">Bo1</option><option value="3">Bo3</option><option value="5">Bo5</option></select></Field><button className="rounded-lg bg-cyan-400 px-4 py-3 text-sm font-black uppercase tracking-[0.12em] text-slate-950 md:col-span-2">Schedule match</button></form><ItemList items={items} empty="No matches scheduled yet." onDelete={async (id) => { await deleteDashboardMatch(id); await load() }} render={(item) => <><strong>{item.team_one_name || 'TBD'} vs {item.team_two_name || 'TBD'}</strong><span>{item.stage} · {item.status} · {item.scheduled_at}</span></>} /></ToolPanel>
}

function ToolPanel({ eyebrow, title, children }) { return <section className="mx-auto mt-8 max-w-7xl rounded-2xl border border-white/10 bg-slate-900/70 p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-300">{eyebrow}</p><h2 className="mt-2 text-2xl font-black">{title}</h2><div className="mt-6">{children}</div></section> }
function ItemList({ items, empty, onDelete, render }) { return <div className="mt-8 space-y-2">{items.length ? items.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-slate-950/60 px-4 py-3"><div className="flex flex-col gap-1">{render(item)}</div><button type="button" onClick={() => onDelete(item.id)} className="rounded-md border border-rose-400/30 px-3 py-2 text-xs font-bold uppercase text-rose-300 hover:bg-rose-400/10">Delete</button></div>) : <p className="rounded-xl border border-dashed border-white/10 p-5 text-sm text-slate-500">{empty}</p>}</div> }